FROM python:3.9

ADD . /app
WORKDIR /app

# RUN apt update
# RUN apt -y upgrade
# RUN apt -y install python3 python3-pip
RUN pip3 install -r requirements.txt

RUN echo 'This is a file' > data.txt

CMD python3 client.py --host server --port 5000 send data.txt